---
- name: SSO server configuration playbook
  hosts: sso
  become: true
  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"

    - name: Disable all RHSM repositories
      community.general.rhsm_repository:
        name: '*'
        state: disabled

    - name: Enable required RHSM repositories
      community.general.rhsm_repository:
        name:
          - jb-eap-7.4-for-rhel-8-x86_64-rpms
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - rh-sso-7.6-for-rhel-8-x86_64-rpms
        state: enabled

    - name: Ensure all packages are updated
      ansible.builtin.dnf:
        name: '*'
        state: latest # noqa package-latest

    - name: Install SSO packages
      ansible.builtin.dnf:
        name: '@rh-sso7'
        state: latest # noqa package-latest

    - name: Ensure chrony is enabled
      ansible.builtin.service:
        name: chronyd
        enabled: true
        state: started

    - name: Ensure firewalld is enabled
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow ports for SSO
      ansible.posix.firewalld:
        zone: public
        state: enabled
        permanent: true
        port: "{{ item }}"
      loop:
        - 8080/tcp
        - 8443/tcp
        - 9990/tcp
        - 9993/tcp
        - 443/tcp
        - 389/tcp
        - 636/udp

    - name: Reload firewalld service
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Reboot server
      ansible.builtin.reboot:

- name: SSO configuration playbook
  hosts: sso
  tasks:
    - name: Fix permission issues on SSO folders
      ansible.builtin.file:
        path: "{{ item }}"
        owner: jboss
        group: root
        recurse: true
      loop:
        - /opt/rh/rh-sso7/
        - /var/opt/rh/rh-sso7/
      become: true

    - name: Configure admin user
      ansible.builtin.command:
        cmd: "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/add-user-keycloak.sh -u admin -p redhat"
      become: true

    - name: Start keycloak in standalone configuration
      ansible.builtin.service:
        name: rh-sso7
        enabled: true
        state: started
      become: true
