---
- name: SSO server configuration playbook
  hosts: sso
  become: true
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Run SSO setup role
      ansible.builtin.include_role:
        name: sso-setup

- name: SSO configuration playbook
  hosts: sso
  tasks:
    - name: Fix permission issues on SSO folders
      ansible.builtin.file:
        path: "{{ item }}"
        owner: jboss
        group: root
        recurse: true
      loop:
        - /opt/rh/rh-sso7/
        - /var/opt/rh/rh-sso7/
      become: true

    - name: Configure admin user
      ansible.builtin.command:
        cmd: "/opt/rh/rh-sso7/root/usr/share/keycloak/bin/add-user-keycloak.sh -u admin -p redhat"
      become: true

    - name: Start keycloak in standalone configuration
      ansible.builtin.service:
        name: rh-sso7
        enabled: true
        state: started
      become: true
